//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfandi_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Principal\\Banner_Animación.swf")]
        public string Ima_BANNERSUPERIOR {
            get {
                return ((string)(this["Ima_BANNERSUPERIOR"]));
            }
            set {
                this["Ima_BANNERSUPERIOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Principal\\Fondo.JPG")]
        public string Ima_PRINCIPAL_Fondo {
            get {
                return ((string)(this["Ima_PRINCIPAL_Fondo"]));
            }
            set {
                this["Ima_PRINCIPAL_Fondo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Principal\\Turnos.PNG")]
        public string Ima_PRINCIPAL_Turno {
            get {
                return ((string)(this["Ima_PRINCIPAL_Turno"]));
            }
            set {
                this["Ima_PRINCIPAL_Turno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Principal\\Otros_Servicios.PNG")]
        public string Ima_PRINCIPAL_OtrosServicios {
            get {
                return ((string)(this["Ima_PRINCIPAL_OtrosServicios"]));
            }
            set {
                this["Ima_PRINCIPAL_OtrosServicios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Fondo.JPG")]
        public string Ima_SERVICIOS_Fondo {
            get {
                return ((string)(this["Ima_SERVICIOS_Fondo"]));
            }
            set {
                this["Ima_SERVICIOS_Fondo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Btn_Imprimir_Credito.PNG")]
        public string Ima_SERVICIOS_btn_ImprimirCreditos {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_ImprimirCreditos"]));
            }
            set {
                this["Ima_SERVICIOS_btn_ImprimirCreditos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Btn_Pre_Liquidacion.PNG")]
        public string Ima_SERVICIOS_btn_PreLiquidacion {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_PreLiquidacion"]));
            }
            set {
                this["Ima_SERVICIOS_btn_PreLiquidacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Btn_Imprimir_Tarjeta.PNG")]
        public string Ima_SERVICIOS_btn_ImprimirTarjeta {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_ImprimirTarjeta"]));
            }
            set {
                this["Ima_SERVICIOS_btn_ImprimirTarjeta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Btn_Pre_Aprobado.PNG")]
        public string Ima_SERVICIOS_btn_Consulta_PreAprobado {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_Consulta_PreAprobado"]));
            }
            set {
                this["Ima_SERVICIOS_btn_Consulta_PreAprobado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Btn_Saldo.PNG")]
        public string Ima_SERVICIOS_btn_Consulta_Saldo {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_Consulta_Saldo"]));
            }
            set {
                this["Ima_SERVICIOS_btn_Consulta_Saldo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Btn-Ultimo_Pago.PNG")]
        public string Ima_SERVICIOS_btn_Consulta_VisualizarUltimoPago {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_Consulta_VisualizarUltimoPago"]));
            }
            set {
                this["Ima_SERVICIOS_btn_Consulta_VisualizarUltimoPago"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\Btn_Actualizar_Datos.PNG")]
        public string Ima_SERVICIOS_btn_ActualizarDatos {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_ActualizarDatos"]));
            }
            set {
                this["Ima_SERVICIOS_btn_ActualizarDatos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicios\\BT-VOLVER.PNG")]
        public string Ima_SERVICIOS_btn_Volver {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_Volver"]));
            }
            set {
                this["Ima_SERVICIOS_btn_Volver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Principal\\btn_Eliminar_Estado_1.png")]
        public string Ima_AUTENTICACION_btn_Eliminar_Estado_1 {
            get {
                return ((string)(this["Ima_AUTENTICACION_btn_Eliminar_Estado_1"]));
            }
            set {
                this["Ima_AUTENTICACION_btn_Eliminar_Estado_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Principal\\btn_Eliminar_Estado_2.png")]
        public string Ima_AUTENTICACION_btn_Eliminar_Estado_2 {
            get {
                return ((string)(this["Ima_AUTENTICACION_btn_Eliminar_Estado_2"]));
            }
            set {
                this["Ima_AUTENTICACION_btn_Eliminar_Estado_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Principal\\AnimaciónEspera.swf")]
        public string Ima_PRINCIPAL_Animacion_Espera {
            get {
                return ((string)(this["Ima_PRINCIPAL_Animacion_Espera"]));
            }
            set {
                this["Ima_PRINCIPAL_Animacion_Espera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicio\\Fondo.JPG")]
        public string Ima_SERVICIO_Fondo {
            get {
                return ((string)(this["Ima_SERVICIO_Fondo"]));
            }
            set {
                this["Ima_SERVICIO_Fondo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicio\\btn_Imprimir.PNG")]
        public string Ima_SERVICIO_btn_Imprimir {
            get {
                return ((string)(this["Ima_SERVICIO_btn_Imprimir"]));
            }
            set {
                this["Ima_SERVICIO_btn_Imprimir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Pagina_Servicio\\btn_MenuPrincipal.PNG")]
        public string Ima_SERVICIO_btn_MenuPrincipal {
            get {
                return ((string)(this["Ima_SERVICIO_btn_MenuPrincipal"]));
            }
            set {
                this["Ima_SERVICIO_btn_MenuPrincipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Principal\\btn_Ingresar.PNG")]
        public string Ima_AUTENTICACION_btn_Login {
            get {
                return ((string)(this["Ima_AUTENTICACION_btn_Login"]));
            }
            set {
                this["Ima_AUTENTICACION_btn_Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagenes\\Principal\\btn_Aceptar.PNG")]
        public string Ima_SERVICIOS_btn_Aceptar {
            get {
                return ((string)(this["Ima_SERVICIOS_btn_Aceptar"]));
            }
            set {
                this["Ima_SERVICIOS_btn_Aceptar"] = value;
            }
        }
    }
}
